"""agents 表新增 is_preset/description/created_by

Revision ID: 165d793da2cd
Revises: 7a2b1c9d66de
Create Date: 2026-09-10 19:14:34.003838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165d793da2cd'
down_revision: Union[str, Sequence[str], None] = '7a2b1c9d66de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('agents', sa.Column('is_preset', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('created_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'created_by')
    op.drop_column('agents', 'is_preset')
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
