"""baseline: 创建初始四张表

Revision ID: 7a2b1c9d66de
Revises: 
Create Date: 2026-09-10 19:14:09.276320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2b1c9d66de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('taste', sa.String(length=16), nullable=False),
    sa.Column('budget', sa.String(length=16), nullable=False),
    sa.Column('weather', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_table('debate_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('speaker_id', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_rounds_created_at'), 'debate_rounds', ['created_at'], unique=False)
    op.create_index(op.f('ix_debate_rounds_round_number'), 'debate_rounds', ['round_number'], unique=False)
    op.create_index(op.f('ix_debate_rounds_session_id'), 'debate_rounds', ['session_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('final_choice', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('pros', sa.JSON(), nullable=False),
    sa.Column('cons', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('winner_agent', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_session_id'), 'recommendations', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_session_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_debate_rounds_session_id'), table_name='debate_rounds')
    op.drop_index(op.f('ix_debate_rounds_round_number'), table_name='debate_rounds')
    op.drop_index(op.f('ix_debate_rounds_created_at'), table_name='debate_rounds')
    op.drop_table('debate_rounds')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('agents')
    # ### end Alembic commands ###
